from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('menu/', views.menu, name='menu'),
    path('menu/<str:category>/', views.menu, name='menu_category'),
    path('order/', views.order, name='order'),
    path('manage_menu/', views.manage_menu, name='manage_menu'),
    path('edit_menu_item/<int:item_id>/', views.edit_menu_item, name='edit_menu_item'),
    path('delete_menu_item/<int:item_id>/', views.delete_menu_item, name='delete_menu_item'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('order/', views.order, name='order'),
    path('popular_menu/', views.popular_menu, name='popular_menu'),
    path('reorder/', views.reorder, name='reorder'),
    path('review/', views.review, name='review'),
    path('reserve/', views.reserve_table, name='reserve_table'),
    path('manager/', views.manager, name='manager'),
    path('staff/', views.staff, name='staff'),
    path('know_the_food_taste/', views.know_the_food_taste, name='know_the_food_taste'),
    path('location/', views.location, name='location'),
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('custom-admin/', views.admin_page, name='custom_admin'),
    path('manage_users/', views.manage_users, name='manage_users'),  # Correct the URL pattern here
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add_user/', views.add_user, name='add_user'),
    path('manage-users/', views.manage_users, name='manage_users'),
    path('manage-staff/', views.manage_staff, name='manage_staff'),
    path('manage-reservations/', views.manage_reservations, name='manage_reservations'),
    path('manage-orders/', views.manage_orders, name='manage_orders'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('add-user/', views.add_user, name='add_user'),
    path('manage_reservations/', views.manage_reservations, name='manage_reservations'),
    path('reservation_success/', views.reservation_success, name='reservation_success'),
    path('edit_reservation/<int:reservation_id>/', views.edit_reservation, name='edit_reservation'),
    path('delete_reservation/<int:reservation_id>/', views.delete_reservation, name='delete_reservation'),
]
